
Algoritmo "CRESCENTE"

Var
   x, y: inteiro
   


Inicio
      escreva("Digite dois numeros: ")
      leia(x)
      leia(y)

      enquanto x <> y faca

      se x < y entao
         escreval("CRECENTE")
      senao
         escreval("DECRESCENTE")
      fimse

      escreval("Digite outros dois numeros ")
      leia(x)
      leia(y)
      
      fimenquanto
Fimalgoritmo
